services:
  backend:
    # image: python:3.13.4-slim-bullseye
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0 --port 8000
    environment:
      - PORT=8000
      - MY_PROJECT=Hello World
    env_file:
      - .env.sample
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: backend\requirements.txt
        - action: rebuild
          path: backend\Dockerfile
        - action: restart
          path: backend\src\

  static_html:
    # image: python:3.13.4-slim-bullseye
    build:
      context: ./static_html
      dockerfile: static.Dockerfile
    ports:
      - "8000:8000"
    command: python -m http.server 8000
    volumes:
      - ./static_html/src:/app